version: "3"
services:
  app:
    container_name: employee-mysql
    image: employeee-image
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - mysql_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/testing?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
  mysql_db:
    image: "mysql/mysql-server"
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: testing
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
